# Generated by Django 6.1 on 2026-09-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('image', models.URLField()),
                ('author', models.CharField(max_length=20)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('read_time', models.IntegerField()),
            ],
        ),
    ]
